
package View;
import Controlador.ControladorPaciente;
import Controlador.ControladorProfesional;
import Controlador.ControladorEstudios;
import javax.swing.JFrame;

public class GestionInformacion extends javax.swing.JFrame {

    /**
     * Creates new form GestionInformacion
     */
    public GestionInformacion() {
        initComponents();
        this.setLayout(new java.awt.GridBagLayout());
        this.getContentPane().setBackground(jPanel1.getBackground());
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EstudiosInicio = new javax.swing.JButton();
        ProfesionalInicio = new javax.swing.JButton();
        PacienteInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(154, 202, 237));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Laboratorio de Análisis Clínicos Java SRL");

        EstudiosInicio.setBackground(new java.awt.Color(109, 146, 197));
        EstudiosInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EstudiosInicio.setForeground(new java.awt.Color(255, 255, 255));
        EstudiosInicio.setText("Estudios");

        ProfesionalInicio.setBackground(new java.awt.Color(109, 146, 197));
        ProfesionalInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProfesionalInicio.setForeground(new java.awt.Color(255, 255, 255));
        ProfesionalInicio.setText("Profesionales");
        ProfesionalInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfesionalInicioActionPerformed(evt);
            }
        });

        PacienteInicio.setBackground(new java.awt.Color(109, 146, 197));
        PacienteInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PacienteInicio.setForeground(new java.awt.Color(255, 255, 255));
        PacienteInicio.setText("Pacientes");
        PacienteInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacienteInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(PacienteInicio)
                .addGap(65, 65, 65)
                .addComponent(ProfesionalInicio)
                .addGap(79, 79, 79)
                .addComponent(EstudiosInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PacienteInicio)
                    .addComponent(ProfesionalInicio)
                    .addComponent(EstudiosInicio))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PacienteInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacienteInicioActionPerformed
        // TODO add your handling code here:
        View.GestionPacientes gp = new View.GestionPacientes(); 
        gp.setVisible(true);
        gp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_PacienteInicioActionPerformed

    private void ProfesionalInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfesionalInicioActionPerformed
        // TODO add your handling code here:
        View.GestionProfesionales gp = new View.GestionProfesionales(); 
        gp.setVisible(true);
        gp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ProfesionalInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionInformacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EstudiosInicio;
    private javax.swing.JButton PacienteInicio;
    private javax.swing.JButton ProfesionalInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
